"""image_enhancements_and_analytics

Revision ID: 0f1ff944e5d9
Revises: abd27417f632
Create Date: 2025-11-24 08:46:51.619335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1ff944e5d9'
down_revision: Union[str, Sequence[str], None] = 'abd27417f632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('hover_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_clicked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_analytics_project_id'), 'project_analytics', ['project_id'], unique=True)
    op.create_table('project_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_events_created', 'project_events', ['created_at'], unique=False)
    op.create_index('idx_project_events_type', 'project_events', ['project_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_project_events_created_at'), 'project_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_events_project_id'), 'project_events', ['project_id'], unique=False)
    op.add_column('project_images', sa.Column('thumbnail_url', sa.String(length=512), nullable=True))
    op.add_column('project_images', sa.Column('alt_text', sa.String(length=256), nullable=True))
    op.add_column('project_images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('project_images', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('project_images', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('project_images', sa.Column('mime_type', sa.String(length=64), nullable=True))
    op.add_column('project_images', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_images', 'is_featured')
    op.drop_column('project_images', 'mime_type')
    op.drop_column('project_images', 'file_size')
    op.drop_column('project_images', 'height')
    op.drop_column('project_images', 'width')
    op.drop_column('project_images', 'alt_text')
    op.drop_column('project_images', 'thumbnail_url')
    op.drop_index(op.f('ix_project_events_project_id'), table_name='project_events')
    op.drop_index(op.f('ix_project_events_created_at'), table_name='project_events')
    op.drop_index('idx_project_events_type', table_name='project_events')
    op.drop_index('idx_project_events_created', table_name='project_events')
    op.drop_table('project_events')
    op.drop_index(op.f('ix_project_analytics_project_id'), table_name='project_analytics')
    op.drop_table('project_analytics')
    # ### end Alembic commands ###
