"""core_model_fixes_dates_indexes_timestamps

Revision ID: 368d07e63923
Revises: 1bb618a06316
Create Date: 2025-11-24 08:05:45.562263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '368d07e63923'
down_revision: Union[str, Sequence[str], None] = '1bb618a06316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_table('entities')
    
    # Add timestamps to translation tables
    op.add_column('certification_translations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('certification_translations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_certification_translations_certification_id'), 'certification_translations', ['certification_id'], unique=False)
    op.drop_constraint(op.f('certification_translations_certification_id_fkey'), 'certification_translations', type_='foreignkey')
    op.create_foreign_key(None, 'certification_translations', 'certifications', ['certification_id'], ['id'], ondelete='CASCADE')
    
    # Convert certification dates: String -> Date
    # Step 1: Add temporary Date columns
    op.add_column('certifications', sa.Column('issue_date_new', sa.Date(), nullable=True))
    op.add_column('certifications', sa.Column('expiry_date_new', sa.Date(), nullable=True))
    
    # Step 2: Migrate data - convert string dates to Date
    # Handle formats like "2020-01-15", "2020-01", or NULL
    op.execute("""
        UPDATE certifications 
        SET issue_date_new = CASE 
            WHEN issue_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN issue_date::date
            WHEN issue_date ~ '^[0-9]{4}-[0-9]{2}$' THEN (issue_date || '-01')::date
            ELSE NULL
        END
    """)
    op.execute("""
        UPDATE certifications 
        SET expiry_date_new = CASE 
            WHEN expiry_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN expiry_date::date
            WHEN expiry_date ~ '^[0-9]{4}-[0-9]{2}$' THEN (expiry_date || '-01')::date
            ELSE NULL
        END
    """)
    
    # Step 3: Drop old columns and rename new ones
    op.drop_column('certifications', 'issue_date')
    op.drop_column('certifications', 'expiry_date')
    op.alter_column('certifications', 'issue_date_new', new_column_name='issue_date')
    op.alter_column('certifications', 'expiry_date_new', new_column_name='expiry_date')
    
    # Update server defaults for certifications
    op.alter_column('certifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('certifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    
    # Add timestamps to courses
    op.add_column('courses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('courses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_courses_education_id'), 'courses', ['education_id'], unique=False)
    op.drop_constraint(op.f('courses_education_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'educations', ['education_id'], ['id'], ondelete='CASCADE')
    
    # Add timestamps to education translations
    op.add_column('education_translations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('education_translations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_education_translations_education_id'), 'education_translations', ['education_id'], unique=False)
    op.drop_constraint(op.f('education_translations_education_id_fkey'), 'education_translations', type_='foreignkey')
    op.create_foreign_key(None, 'education_translations', 'educations', ['education_id'], ['id'], ondelete='CASCADE')
    
    # Convert education dates: String -> Date
    op.add_column('educations', sa.Column('start_date_new', sa.Date(), nullable=True))
    op.add_column('educations', sa.Column('end_date_new', sa.Date(), nullable=True))
    
    op.execute("""
        UPDATE educations 
        SET start_date_new = CASE 
            WHEN start_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN start_date::date
            WHEN start_date ~ '^[0-9]{4}-[0-9]{2}$' THEN (start_date || '-01')::date
            ELSE NULL
        END
    """)
    op.execute("""
        UPDATE educations 
        SET end_date_new = CASE 
            WHEN end_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN end_date::date
            WHEN end_date ~ '^[0-9]{4}-[0-9]{2}$' THEN (end_date || '-01')::date
            ELSE NULL
        END
    """)
    
    op.drop_column('educations', 'start_date')
    op.drop_column('educations', 'end_date')
    op.alter_column('educations', 'start_date_new', new_column_name='start_date')
    op.alter_column('educations', 'end_date_new', new_column_name='end_date')
    
    op.alter_column('educations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('educations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    
    # Update experience_tags cascade
    op.drop_constraint(op.f('experience_tags_tag_id_fkey'), 'experience_tags', type_='foreignkey')
    op.drop_constraint(op.f('experience_tags_experience_id_fkey'), 'experience_tags', type_='foreignkey')
    op.create_foreign_key(None, 'experience_tags', 'experiences', ['experience_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'experience_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    
    # Add timestamps to experience translations
    op.add_column('experience_translations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('experience_translations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_experience_translations_experience_id'), 'experience_translations', ['experience_id'], unique=False)
    op.drop_constraint(op.f('experience_translations_experience_id_fkey'), 'experience_translations', type_='foreignkey')
    op.create_foreign_key(None, 'experience_translations', 'experiences', ['experience_id'], ['id'], ondelete='CASCADE')
    
    # Convert experience dates: String -> Date
    op.add_column('experiences', sa.Column('start_date_new', sa.Date(), nullable=True))
    op.add_column('experiences', sa.Column('end_date_new', sa.Date(), nullable=True))
    
    op.execute("""
        UPDATE experiences 
        SET start_date_new = CASE 
            WHEN start_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN start_date::date
            WHEN start_date ~ '^[0-9]{4}-[0-9]{2}$' THEN (start_date || '-01')::date
            ELSE NULL
        END
    """)
    op.execute("""
        UPDATE experiences 
        SET end_date_new = CASE 
            WHEN end_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN end_date::date
            WHEN end_date ~ '^[0-9]{4}-[0-9]{2}$' THEN (end_date || '-01')::date
            ELSE NULL
        END
    """)
    
    op.drop_column('experiences', 'start_date')
    op.drop_column('experiences', 'end_date')
    op.alter_column('experiences', 'start_date_new', new_column_name='start_date')
    op.alter_column('experiences', 'end_date_new', new_column_name='end_date')
    
    op.alter_column('experiences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('experiences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    
    # Update profiles location type - requires USING clause for PostgreSQL
    op.execute("ALTER TABLE profiles ALTER COLUMN location TYPE JSON USING location::json")
    
    # Add timestamps to skill translations
    op.add_column('skill_translations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('skill_translations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_skill_translations_skill_id'), 'skill_translations', ['skill_id'], unique=False)
    op.drop_constraint(op.f('skill_translations_skill_id_fkey'), 'skill_translations', type_='foreignkey')
    op.create_foreign_key(None, 'skill_translations', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    
    # Update skills timestamps
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    
    # Add timestamps to tags
    op.add_column('tags', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(None, 'skill_translations', type_='foreignkey')
    op.create_foreign_key(op.f('skill_translations_skill_id_fkey'), 'skill_translations', 'skills', ['skill_id'], ['id'])
    op.drop_index(op.f('ix_skill_translations_skill_id'), table_name='skill_translations')
    op.drop_column('skill_translations', 'updated_at')
    op.drop_column('skill_translations', 'created_at')
    op.alter_column('profiles', 'location',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('experiences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('experiences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('experiences', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('experiences', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_constraint(None, 'experience_translations', type_='foreignkey')
    op.create_foreign_key(op.f('experience_translations_experience_id_fkey'), 'experience_translations', 'experiences', ['experience_id'], ['id'])
    op.drop_index(op.f('ix_experience_translations_experience_id'), table_name='experience_translations')
    op.drop_column('experience_translations', 'updated_at')
    op.drop_column('experience_translations', 'created_at')
    op.drop_constraint(None, 'experience_tags', type_='foreignkey')
    op.drop_constraint(None, 'experience_tags', type_='foreignkey')
    op.create_foreign_key(op.f('experience_tags_experience_id_fkey'), 'experience_tags', 'experiences', ['experience_id'], ['id'])
    op.create_foreign_key(op.f('experience_tags_tag_id_fkey'), 'experience_tags', 'tags', ['tag_id'], ['id'])
    op.alter_column('educations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('educations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('educations', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('educations', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_constraint(None, 'education_translations', type_='foreignkey')
    op.create_foreign_key(op.f('education_translations_education_id_fkey'), 'education_translations', 'educations', ['education_id'], ['id'])
    op.drop_index(op.f('ix_education_translations_education_id'), table_name='education_translations')
    op.drop_column('education_translations', 'updated_at')
    op.drop_column('education_translations', 'created_at')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_education_id_fkey'), 'courses', 'educations', ['education_id'], ['id'])
    op.drop_index(op.f('ix_courses_education_id'), table_name='courses')
    op.drop_column('courses', 'updated_at')
    op.drop_column('courses', 'created_at')
    op.alter_column('certifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('certifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('certifications', 'expiry_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('certifications', 'issue_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_constraint(None, 'certification_translations', type_='foreignkey')
    op.create_foreign_key(op.f('certification_translations_certification_id_fkey'), 'certification_translations', 'certifications', ['certification_id'], ['id'])
    op.drop_index(op.f('ix_certification_translations_certification_id'), table_name='certification_translations')
    op.drop_column('certification_translations', 'updated_at')
    op.drop_column('certification_translations', 'created_at')
    op.create_table('entities',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('entities_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entities_pkey'),
    sa.UniqueConstraint('slug', name='entities_slug_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('translations_entity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('translations_pkey'))
    )
    # ### end Alembic commands ###
