"""url_refactoring_multiple_urls

Revision ID: abd27417f632
Revises: 368d07e63923
Create Date: 2025-11-24 08:41:42.217272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abd27417f632'
down_revision: Union[str, Sequence[str], None] = '368d07e63923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Create project_urls table
    op.create_table('project_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'url_type', name='uq_project_url_type')
    )
    op.create_index('idx_project_urls_project', 'project_urls', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_urls_project_id'), 'project_urls', ['project_id'], unique=False)
    
    # Step 2: Migrate existing URL data
    # Handle both JSON format {"github": "...", "live": "..."} and plain string URLs
    op.execute("""
        INSERT INTO project_urls (project_id, url_type, url, "order")
        SELECT 
            id as project_id,
            CASE 
                WHEN url LIKE '{%' THEN 'github'  -- JSON format, extract github first
                ELSE 'live'  -- Plain string, assume it's a live URL
            END as url_type,
            CASE 
                WHEN url LIKE '{%' THEN 
                    COALESCE(
                        (url::json->>'github')::text,
                        (url::json->>'url_github')::text
                    )
                ELSE url
            END as url,
            0 as "order"
        FROM projects 
        WHERE url IS NOT NULL 
        AND url != ''
        AND (
            url NOT LIKE '{%' 
            OR (url::json->>'github') IS NOT NULL
            OR (url::json->>'url_github') IS NOT NULL
        )
        
        UNION ALL
        
        SELECT 
            id as project_id,
            'live' as url_type,
            COALESCE(
                (url::json->>'live')::text,
                (url::json->>'url_live')::text
            ) as url,
            1 as "order"
        FROM projects 
        WHERE url IS NOT NULL 
        AND url != ''
        AND url LIKE '{%'
        AND (
            (url::json->>'live') IS NOT NULL
            OR (url::json->>'url_live') IS NOT NULL
        )
    """)
    
    # Step 3: Update project_images
    op.add_column('project_images', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_images', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_project_images_project_id'), 'project_images', ['project_id'], unique=False)
    op.drop_constraint(op.f('project_images_project_id_fkey'), 'project_images', type_='foreignkey')
    op.create_foreign_key(None, 'project_images', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    
    # Step 4: Update project_tags
    op.drop_constraint(op.f('project_tags_tag_id_fkey'), 'project_tags', type_='foreignkey')
    op.drop_constraint(op.f('project_tags_project_id_fkey'), 'project_tags', type_='foreignkey')
    op.create_foreign_key(None, 'project_tags', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    
    # Step 5: Update project_translations
    op.add_column('project_translations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_translations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_project_translations_project_id'), 'project_translations', ['project_id'], unique=False)
    op.drop_constraint(op.f('project_translations_project_id_fkey'), 'project_translations', type_='foreignkey')
    op.create_foreign_key(None, 'project_translations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    
    # Step 6: Update projects timestamps
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    
    # Step 7: Drop old url column (data already migrated)
    op.drop_column('projects', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(None, 'project_translations', type_='foreignkey')
    op.create_foreign_key(op.f('project_translations_project_id_fkey'), 'project_translations', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_project_translations_project_id'), table_name='project_translations')
    op.drop_column('project_translations', 'updated_at')
    op.drop_column('project_translations', 'created_at')
    op.drop_constraint(None, 'project_tags', type_='foreignkey')
    op.drop_constraint(None, 'project_tags', type_='foreignkey')
    op.create_foreign_key(op.f('project_tags_project_id_fkey'), 'project_tags', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_tags_tag_id_fkey'), 'project_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'project_images', type_='foreignkey')
    op.create_foreign_key(op.f('project_images_project_id_fkey'), 'project_images', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_project_images_project_id'), table_name='project_images')
    op.drop_column('project_images', 'updated_at')
    op.drop_column('project_images', 'created_at')
    op.drop_index(op.f('ix_project_urls_project_id'), table_name='project_urls')
    op.drop_index('idx_project_urls_project', table_name='project_urls')
    op.drop_table('project_urls')
    # ### end Alembic commands ###
